# SPDX-License-Identifier: Apache-2.0
#
# core_cpp_add_header_self_check()
#
# Compiles every PUBLIC header as the first and only include of a translation unit of its own, so
# that `.agent/rules/cpp-guidelines.md`'s "every header is self-contained" is enforced rather than
# merely stated ([core-cpp#31](https://github.com/contour-terminal/core-cpp/issues/31)).
#
# WHY A COMPILED CHECK. check-cmake-hygiene.cmake has eighteen rules and every one of them reads
# TEXT. None compiles anything, so a header needing a neighbour included first passed every check
# this tree had -- and broke only for whoever included it first, which in a library is a consumer.
# Six consumer migrations are about to include these headers in orders nobody here has tried.
#
# WHY PER-LEG AND NOT `tree-level`. Whether a header stands alone is a question for each toolchain:
# MSVC, clang, GCC, AppleClang and emcc differ in what they transitively drag in, so the same
# header can be self-contained under one and not another. A `tree-level` check answers once for
# every platform, which is exactly what this cannot do, so it rides the build rather than the
# `style` job (Ruling R96).
#
# THE LIST COMES FROM THE BUILD, NEVER A GLOB. Each target's `FILE_SET HEADERS` is the definition
# of its public API, so a header added tomorrow is covered without anyone remembering, and a header
# a platform excludes is excluded here too. That is not a convenience: the WebAssembly subset drops
# headers from the file set (ThreadPoolExecutor.hpp `#error`s under single-threaded Emscripten by
# design), and a glob would compile them there and fail for the wrong reason. Private headers --
# `detail/`, `posix/`, `linux/`, `bsd/`, `windows/`, `emscripten/`, the tui `platform/` directories
# -- are in no file set and so are not in scope, which is correct: an implementation header is
# allowed to assume its includer.
#
# The check IS the build. There is nothing to run afterwards: if the object library compiles, every
# public header stood alone, and if one does not, the compiler names the header and what it needed,
# which is a better diagnostic than any harness would produce.

## @brief Adds one object library per header-publishing target, with a TU per public header.
##
## Each generated unit is compiled with its own target's usage requirements -- include directories,
## compile definitions, and dependencies such as libunicode -- so a header is asked to stand up in
## the environment a consumer linking that target actually gets, not in the union of every module's.
function(core_cpp_add_header_self_check)
    if(NOT CORE_CPP_TESTING)
        return()
    endif()
    get_property(targets GLOBAL PROPERTY CORE_CPP_HEADER_TARGETS)
    if(NOT targets)
        message(FATAL_ERROR
            "core_cpp_add_header_self_check(): no target publishes headers. Either this ran before "
            "core_cpp_add_modules(), or CORE_CPP_HEADER_TARGETS stopped being filled -- and a check "
            "over an empty list reports the same green as a check that passed.")
    endif()

    set(generatedRoot "${CMAKE_CURRENT_BINARY_DIR}/header-self-check")
    set(total 0)
    foreach(target IN LISTS targets)
        get_target_property(headers ${target} HEADER_SET)
        if(NOT headers)
            continue()
        endif()
        get_target_property(baseDirs ${target} HEADER_DIRS)

        set(units "")
        foreach(header IN LISTS headers)
            core_cpp_header_include_path("${header}" "${baseDirs}" includePath)
            if(NOT includePath)
                message(FATAL_ERROR
                    "core_cpp_add_header_self_check(): '${header}' of ${target} is under none of its "
                    "FILE_SET base directories (${baseDirs}), so the angle-bracket spelling a "
                    "consumer would use cannot be derived. Refusing rather than guessing one.")
            endif()
            string(MAKE_C_IDENTIFIER "${includePath}" stem)
            set(unit "${generatedRoot}/${stem}.cpp")
            # CONFIGURE_DEPENDS is deliberately absent: the content depends on the header's PATH,
            # not its contents, so a rewrite of the header must not regenerate this file. What must
            # happen when a header is added or removed is a reconfigure, and the file set changing
            # is what triggers one.
            file(CONFIGURE OUTPUT "${unit}" CONTENT
"// SPDX-License-Identifier: Apache-2.0
// Generated by cmake/CoreCppHeaderSelfCheck.cmake. Do not edit, and do not add an include.
//
// <${includePath}> is the FIRST and ONLY include here, which is the order a consumer reaches it
// in. If it needs a neighbour included first, this translation unit is where that is refused
// (core-cpp#31).
#include <${includePath}>
" @ONLY)
            list(APPEND units "${unit}")
            math(EXPR total "${total} + 1")
        endforeach()

        if(NOT units)
            continue()
        endif()
        set(checkTarget "${target}-header-self-check")
        add_library(${checkTarget} OBJECT ${units})
        # PRIVATE, and the target itself rather than its alias: this consumes the usage
        # requirements and publishes none of its own. Nothing links it -- building it IS the check.
        target_link_libraries(${checkTarget} PRIVATE ${target})
        core_cpp_apply_toolchain(${checkTarget})
        set_target_properties(${checkTarget} PROPERTIES FOLDER "core-cpp/header-self-check")
        list(APPEND checkTargets ${checkTarget})
    endforeach()

    message(STATUS
        "[core-cpp] header self-check: ${total} public header(s) compiled standalone, in "
        "${CMAKE_CURRENT_BINARY_DIR}")
    set_property(GLOBAL PROPERTY CORE_CPP_HEADER_SELF_CHECK_COUNT "${total}")
endfunction()

## @brief Sets @p outVar to @p header spelled relative to whichever of @p baseDirs contains it.
##
## That spelling is the point of the check: `#include <core/net/EventLoop.hpp>` is what a consumer
## writes, and compiling the header by its absolute path would prove something weaker -- that the
## file parses, not that it is reachable and self-contained the way it is published.
function(core_cpp_header_include_path header baseDirs outVar)
    set(${outVar} "" PARENT_SCOPE)
    foreach(baseDir IN LISTS baseDirs)
        file(RELATIVE_PATH candidate "${baseDir}" "${header}")
        if(candidate MATCHES "^\\.\\." OR IS_ABSOLUTE "${candidate}")
            continue()
        endif()
        set(${outVar} "${candidate}" PARENT_SCOPE)
        return()
    endforeach()
endfunction()
